language: node_js

node_js: lts/*
addons:
    chrome: stable

install:
    - npm install

branches:
    only:
        - master

stages:
    - test
    - name: release
      if: branch = master AND type IN (push) AND commit_message !~ /chore\(release\)/

jobs:
    include:
        - stage: test
          script: npm run test
        - stage: release
          node_js: lts/*
          deploy:
              script: sh ./deploy.sh
              provider: script
              skip_cleanup: true
              keep-history: true
